steps:
  - imports:
      align: group
      list_same_align: false
      separate_lists: false
  - language_pragmas:
      align: false
  - trailing_whitespace: {}

language_extensions:
  - MultiParamTypeClasses

  # Yesod set
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
