steps:
  - simple_align:
      cases: true
      top_level_patterns: true
      records: true
  - imports:
      align: group
      separate_lists: false
  - language_pragmas:
      align: false
  # - records: {}
  - trailing_whitespace: {}
# columns: 100

language_extensions:
  - MultiParamTypeClasses

  # Yesod set
  - QuasiQuotes
  - TemplateHaskell
  - TypeFamilies
