sudo: false
language: haskell

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.0.1

services:
  - postgresql

cache:
  directories:
    - $HOME/.ghc
    - $HOME/.cabal
    - $HOME/.stack

before_install:
  - export PATH=/opt/ghc/8.0.1/bin:$PATH

  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64
    | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

before_script:
  - ./db-devel-init.sh

script:
  - ./build.hs --no-terminal --test
