resolver: lts-5.10

packages:
  - .

extra-deps:
  - imap-0.2.0.3  # for Tasknight.Provider.Gmail
  - monadIO-0.10.1.4  # for imap
  - rolling-queue-0.1  # for imap

  - google-oauth2-0.2.1  # for Tasknight.Provider.Gmail

# todo:
#   try libs:
#     - hoauth2
#     - authenticate-oauth
#     - HaskellNet (IMAP)
