resolver: lts-6.18

packages:
  - dashboard
  - ff

  # extra-deps:
  - location:
      git: https://github.com/cblp/google-oauth2.git
      commit: origin/lts6
    extra-dep: true

extra-deps:
  - imap-0.2.0.3          # for Tasknight.Util.IMAP
  - monadIO-0.10.1.4      # for imap
  - rolling-queue-0.1     # for imap

  # - google-oauth2-0.2.1   # for Tasknight.Provider.Gmail

  - email-header-0.4.0  # for Tasknight.Util.IMAP

# TODO:
#   try libs:
#     OAuth2:
#       - hoauth2
#       - authenticate-oauth
