resolver: lts-7.3

packages:
  - dashboard
  - ff
  - trello-api
  - trello-client

  # extra-deps:
  - location:
      git: https://github.com/cblp/google-oauth2.git
      commit: origin/lts6
    extra-dep: true
    # pending: https://github.com/pbrisbin/google-oauth2/pull/3
  - location:
      git: https://github.com/cblp/imap.git
      commit: origin/lts7
    extra-dep: true
    # pending: https://github.com/mkawalec/imap/pull/10

extra-deps:
  # - imap-0.2.0.3          # for Tasknight.Util.IMAP
  - monadIO-0.10.1.4      # for imap
  - rolling-queue-0.1     # for imap

  # - google-oauth2-0.2.1   # for Tasknight.Provider.Gmail

  - email-header-0.4.0  # for Tasknight.Util.IMAP

# TODO:
#   try libs:
#     OAuth2:
#       - hoauth2
#       - authenticate-oauth
