resolver: lts-5.10

packages:
  - tasknight-dashboard

  # local extra-deps:
  - location: ../email-header
    extra-dep: true

extra-deps:
  - imap-0.2.0.3  # for Tasknight.Util.IMAP
  - monadIO-0.10.1.4  # for imap
  - rolling-queue-0.1  # for imap

  - google-oauth2-0.2.1  # for Tasknight.Provider.Gmail

  # FIXME(cblp, 2016-05-09) temporarily local
  # - email-header-0.2.0  # for Tasknight.Util.IMAP

# todo:
#   try libs:
#     OAuth2:
#       - hoauth2
#       - authenticate-oauth
#     IMAP:
#       - HaskellNet

ghc-options:
  tasknight-dashboard: '-Werror'
