resolver: lts-5.18

packages:
  - dashboard
  - ff
  # - frontend # temporarily disabled

extra-deps:
  - imap-0.2.0.3          # for Tasknight.Util.IMAP
  - monadIO-0.10.1.4      # for imap
  - rolling-queue-0.1     # for imap

  - google-oauth2-0.2.1   # for Tasknight.Provider.Gmail
  # TODO(cblp, 2016-06-25) make google-oauth2 support more recent aeson

  - email-header-0.4.0  # for Tasknight.Util.IMAP

# TODO:
#   try libs:
#     OAuth2:
#       - hoauth2
#       - authenticate-oauth
#     IMAP:
#       HaskellNet:
#         '+': stackage
