resolver: lts-5.17

packages:
  - dashboard
  - frontend

  # TODO(cblp, 2016-07-04) extract
  - dropbox

  # extra-deps:
  - location:
      git: https://github.com/knrafto/email-header
      commit: f9c131292b17c41d05ad8def53937e5baf178bc6
      # 0.2.0 + my fixes
    extra-dep: true

extra-deps:
  - imap-0.2.0.3          # for Tasknight.Util.IMAP
  - monadIO-0.10.1.4      # for imap
  - rolling-queue-0.1     # for imap

  - google-oauth2-0.2.1   # for Tasknight.Provider.Gmail
  # TODO(cblp, 2016-06-25) make google-oauth2 support more recent aeson

  # FIXME(cblp, 2016-05-09) temporarily local
  # - email-header-0.2.0+cblp  # for Tasknight.Util.IMAP

  - servant-0.6.1         # for tasknight-frontend:Tasknight.Frontend
  - servant-blaze-0.6.1   # for servant
  - servant-server-0.6.1  # for servant

# TODO:
#   try libs:
#     OAuth2:
#       - hoauth2
#       - authenticate-oauth
#     IMAP:
#       HaskellNet:
#         '+': stackage
