name: ff
version: 0.0.1

executables:
  ff:
    source-dirs: exe
    main: Main.hs

ghc-options: -Wall -threaded -rtsopts -with-rtsopts=-N

dependencies:
  - base
  - bytestring
  - filepath
  - http-client
  - http-client-tls
  - mtl
  - optparse-applicative
  - text
  - transformers
  - xdg-basedir
  - yaml
  # project
  - trello-client
