name: ff
version: 0.0.1

executables:
  ff:
    source-dirs: exe
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - base
      - http-client
      - http-client-tls
      - mtl
      - optparse-applicative

      - trello-client

ghc-options: -Wall
